6.times do
  cat = Category.create(
    label: Faker::Educator.subject
  )

  4.times do
    post = Post.create(
    title: Faker::Marketing.buzzwords.titleize,
    body: [
      "
      <p>Are the days of ordering an XXL latte or popping a prescription pill to boost focus coming to an end?</p>
      <p>Workplace burnout is now the “occupational phenomenon” circulating the collective health radar. And, as such, stressed Americans struggling with work-life balance are on a quest for healthier alternatives to solutions such as Adderall or caffeine. Last year, the former inspired Netflix’s documentary Take Your Pills, which highlighted the extreme dependence on amphetamines that our national obsession with 24/7 productivity has created. And this year, across the pond, royal health routines made waves when Prince William dropped caffeine at Meghan Markle’s encouragement.</p>
      <p>I was a New York City transplant when I requested my first Adderall prescription—but I still flew home for an appointment with my childhood doctor to take his temperature on the idea. “You’ve always had ADD,” he said gently, underlining that we’d never discussed treatment, especially with something as powerful as an amphetamine. Still, I pushed for the tiny blue pills, and they fired up my productivity just as I’d hoped. But after some time I realized: To maintain that same rush of potential over time, it would require more, and more, and more. Five milligrams turned into ten, which then turned into twenty on a time-release basis. Eventually, my body started to change (a byproduct of never feeling like eating), and I wondered if my hyper-interested conversations surrounding any and every topic were becoming more of a distraction than a social asset.</p>
      <p>To circumvent complete reliance, I decided to stop refilling my prescription when I accepted a job at Vogue. But in lieu of Adderall, I started drinking coffee. It wasn’t exactly the best part of waking up, but it was always around, and I needed some kind of energy fix for 8 a.m. mornings and late-night writing sessions. Each day, I’d make my way to the Condé Nast cafeteria and fill up a Big Gulp–sized cup of iced hazelnut liquid, leaving the cashier slightly wide-eyed at my choice beverage. To avoid hopscotching from stimulant to stimulant, I decided to start weaning myself off my reliance again, foregoing coffee in favor of some more experimental wellness offerings that I hoped would be milder focus aids. From smart stickers to adaptogenic tonics, here’s what’s helped me:</p>
      <p><strong>Giving Up Stimulants</strong></p>
      <p>When interviewing nutritionists, it’s often difficult to get a straight answer as to whether caffeine is really good or bad for us. Some think it can help boost mood. Others note that it can burn out adrenals and spike cortisol levels. “Caffeine can induce adrenal fatigue and put your body in fight-or-flight mode,” explains nutritionist Maya Feller, M.S., R.D., C.D.N. “When we put our body in excessive adrenal stress, our body shifts from processing mode to fight-sleep mode and cortisol levels increase.” As an alternative, I tested herbal brain tonics, organic mushroom powders, and even frequency stickers. Some effects were negligible, but a few options created real results. And it’s a new direction that many doctors are now considering. “Struggle with focus has a lot to do with distractions such as social media, requirements and responsibility at work, and with family,” says Dr. Richard Firshein, a leading expert in integrative and precision-based medicine. Firshein begins by looking for underlying causes of fatigue or the ability to focus, such as hormone imbalance or conditions such as hypothyroidism, hypoglycemia, chronic fatigue syndrome, or Lyme disease. Once they’ve been ruled out, he’ll consider prescribing supplements.” New York City psychologist and licensed mental health counselor Montana Queler, Ph.D., L.M.H.C. wonders if what we call “focus” or “concentration” is more of an addiction to the adrenaline rush that caffeine and prescriptions provide. “Are we actually running on empty, filling ourselves with ersatz fuel? When productivity is propped up as a foremost value, will we ever have enough energy, or will the bar for output rise perpetually beyond reach?” Queler asks of our cultural norm and interest in alternative therapies. “If some of the tools coming to market now are meant to help bring us back into balance, that feels, to me, like a much more sustainable type of energy to be harnessing.” </p>
      <p><strong>Sipping Adaptogenic Tonic</strong></p>
      <p>After taking adaptogenic powders for years, I was intrigued by the “clinical levels” of herbs in Elements by Lokai, which released an adaptogenic tonic called Focus last month. A few droppers into a glass of water later, I noticed an upgrade in the speed at which I was checking off my to-do list. Pitches for stories were flowing all day, yet at night, I was able to fall right to sleep without the usual jittery extended caffeine release. Its main ingredients, blueberry and schisandra, are well documented, after all. “Blueberry has compounds called anthocyanins, which are associated with having an effect on memory,” Feinstein explains. “Studies show blueberries act through specific signaling pathways in the hippocampus that control learning and memory.” And for schisandra, which belongs to a specific group of Chinese herbs, Feinstein notes similar benefits. “It has been traditionally believed to be a supplement that withstands stress and improves memory and cognition,” he says. Queler agrees that it would make sense that the specific blend could indeed “be useful given that it addresses rebalancing cortisol, an imbalance often exacerbated by the stress of pushing ourselves way too hard.”</p>
      <p><strong> Practicing Mindful Meditation </strong></p>
      <p> For many experts, meditation is the inevitable holistic route to a steadier attention span. “Generally, when patients describe having problems with focus, one of the best ways to get started is with guided meditation or a meditation app,” says Firshein, calling out Buddhify as a vetted a starter option. “Meditation has been shown to reduce the effects of cortisol and adrenalin, which are neurotoxic. Allowing your brain to pause and relax is like setting the reset button, giving your brain a chance to reconnect and prioritize thoughts so you’re able to focus on issues and problems that have a higher level of priority than others.” Queler seconds the practice from personal experience. “As someone who has dabbled in meditation, I have had glimpses of a different kind of focus that feels far less manic or busy,” she shares. “Unlike the rush that stimulants provide, meditation offers a calm kind of focus; it’s a quieting of the mind.” And in addition to guided apps, it’s being reimagined into modern, even Spotify-accessible forms. Right now, I’m listening to Kyoto Window, an album of ambient music by Anders Rhedin of the band Dinner. This latest solo release via Captured Tracks is meant to translate the practice of meditation into sound. “I need relaxation and mental clarity as much as anyone,” he notes in his Instagram post announcing the drop. As the synthy sounds move through my headphones, I imagine rippling waves, rolling hills, and looking up at sunbeams streaming through trees. But really, I’m here. In front of a screen. And my work for the day is complete. </p>
      ",

      "<p>We’ve all heard the saying,'Children don’t come with an instruction manual.' It’s true that parenting is no easy feat, and it was a lot tougher before the days of the internet. However, as the 21st century plows ahead, it’s become increasing clear that children do come with an instruction manual -- and it’s called Google.</p>
      <p>There is an endless stream of parenting blogs offering everything from teething advice to reviews on the latest Disney flick, and it may seem a daunting task to narrow them down into a well curated list of sites to turn to when your child has just refinished your hardwood floors with nail polish. Luckily for you, we did all the hard work already.</p>
      <p>We all know new environments and schedules can throw kids for a loop, so give them plenty of time and info to get ready. Get them excited about your vacation destination through picture books or online videos. If this is their first time on a plane, talk through the process of security lines, boarding, and taking off, so they’ll know what to expect.</p>
      <p>It was a kind of charge, across the level, gravelly parade-ground, and the boys were marching well, but right before them stood a high and frowning stone wall and it was of no use to charge against it. It could neither be broken through nor climbed and this one boy, in the middle of the line, was staring at it as if he hated it, while he marched. His feet kept time with the music and perfect pace with the feet of the other boys, but there was an angry look in his black eyes and a hot flush on his face, as if the wall had spoken to him, saying something to rouse his temper and make him answer back. What he did say, was, in a whisper that the next boy to him heard.</p>
      <p>Very nearly all of them, white or colored, moved as if they liked the idea of being young soldiers, but they had not been recruited like other soldiers. Some of them were there because they had no other home to go to nor any other school to be taught in. Many, however, were there for other reasons. For instance, that tall young fellow in command of the foremost company. The captain, in bright uniform who handled his men so well. He is here for highway robbery and it will be a long time before they let him out, although he is one of the best behaved boys in the House of Refuge. He is not here altogether as a punishment, however, nor are any of his companions, no matter what their fault was. This is not a place of judgment, but of help and hope, and, not long ago, a well-known literary man, after inspecting the whole institution, said to the Superintendent.</p>
      ",

      "<p>Last-minute rushing to catch a train or flight is stressful. Dragging kicking and screaming kids along is soul-crushing. Leave extra time to get to the airport or wake up a few minutes early to enjoy a leisurely breakfast if you have to get on the road by a certain time.</p>
      <p>Today is a good day for love, ladies and gents. Today, Modern Family star Sarah Hyland and Bachelorette alum Wells Adams finally announced their engagement. I mean, they’ve been happily dating and so very clearly head-over-heels for each other for over a year, so it’s not like this is a surprise. But we’re reaching for the tissues anyway.</p>
      <p>Nevertheless, before setting out on that errand, he went down into the garden and took a long look at all the land which had been walled in. It might be as good as ever, for a garden, but it had a queer, shut-up appearance.</p>
      <p>'Where’s Billy?' he inquired, aloud. “Hullo. There he is, out on the avenue. How did the old rascal foot it up that wall?”</p>
      <p>There was Billy, indeed, with his toes on the very edge, and with a wisp of something green sticking out at one side of his mouth.</p>
      <p>'Greens!' exclaimed Rodney. 'He can steal from a grocer’s wagon better than any other goat I know of. We used to have a garden. Tell you what, we can make garden of our lots and all the others, too, if we can only have it ploughed. But how would a horse and plough ever get down here?'</p>
      <p>It was a pretty deep question and he gave it up, for that time. In a minute more he was upstairs and out through the window, on his errand to Pat. So far as he knew, he left the house without a living soul in it, but before he reached the next corner, the door of the little back bedroom, at the head of the stairs, went to with a sharp slam. It must have been a strong draft of air that did it, or else the door shut itself.</p>
      ",
    

      "<p>The thing about cut-offs is how surprisingly versatile they are, going from beach to dinner with just a few swaps. Emily favors throwing on a blazer to make them dinner-appropriate, while Jess embraces them as weekend warriors, and Leslie brings her pair to every beach day. Now that it's upwards of 90 degrees in L.A. each day, we thought we'd share three simple ways to style cut-offs this summer, and where we wear each style: </p>
      <p>A blazer may not be the first thing you reach for with denim cut-offs, but it's actually the perfect final touch. Because cut-offs are so quintessentially casual, they require a 'high' option to balance-out the 'low' look if you want to wear them anywhere more dressed-up than the beach. To make the outfit look just a bit more intentional and pulled together, I added a pearl clip and heels along with the blazer, options that may feel overdone if not offset by the shorts.</p>
      <p>I don't wear denim cut-offs often (in fact, I nearly got rid of them when I did a recent closet overhaul), but I kept a pair for beach days, since there really is nothing more effortless for a day in the sun. This weekend, I threw on a black one-piece with cut-offs and slides after a hike in Malibu, which took me from a post-hike dip in the ocean to a casual brunch with friends. I want my weekend outfits to be as carefree and go-with-the-flow as the day—and this turned out to be the perfect combo. </p>
      <p>Is it bold to wear heels and cutoffs? Absolutely. But I like to offset the serious (and extremely pale) amount of leg with an oversized, white linen shirt. If I was feeling a bit more low key, I'd wear the same outfit with my high top black Converse. </p>
      ",

      "<p>Walk into pretty much any wine shop in the U.S. right now and you’ll find a section full of rosés from all over the world, front and center. There’s no reason to settle for the flavorless, pale salmon 'summer water' you’ve come to rely on for beach days and BBQs. Rosé’s explosion in popularity has led to interesting experimentation—perhaps now more than ever, you can find an incredible range of rosé styles, flavor profiles, and shades at an accessible price point.</p>
      <p>Throw out preconceived notations about rosé that you’ve picked up somewhere along the way. Despite what you might think, rosé that’s darker-hued isn’t necessarily sweeter—color and sweetness are not correlated when it comes to rosé. And maybe you’ve been taught that only Provence makes good rosés. Wrong! While there are many great rosés that come from Provence, they also have their fair share of largely mediocre bottles these days, too. (The region currently makes more than 160 million bottles of rosé per year—there’s bound to be some bad ones in the mix.) And, if you thought only good rosé comes in bottles, don’t be afraid to try different formats. These days, some excellent rosé wines come in cans, forties, and even boxes.</p>
      <p>To get you started on this new rosé way, we’ve selected some noteworthy wines—some new, some funky, some just plain fun—to seek out now:</p>
      <p><strong>Los Bermejos Listan Negro Rosado, $23</strong></p>
      <p>The Canary Islands are certainly hot in the wine world right now, but Los Bermejos, on the island of Lanzarote, has been making an incredible rosado for quite some time and remains a perennial favorite of pink drinkers. Made of 100% Listan Negro grapes (indigenous to the region), this deep-hued rosado is crisp and refreshing and pairs beautifully with a nice steak straight off the grill. Note: Before you judge it for its rich color, just try it.</p>
      ",
      
      "<p>Being confined to the house with no one to talk to but a non-verbal, babbling baby day after day is enough to make anyone go a little crazy. Women’s response to the isolation of motherhood has come in the form of Moms Groups. There are countless clans, both formal an informal, for every type of mom, in almost every city and town, where moms can get out, talk to other mothers, and commiserate about new parenthood. But what about the dads? In honor of Father’s Day this month, today’s Mom Dad Talk comes to you from Will Georgantas, a stay-at-home dad to Aristides, 11 months. He dreamt up his one-man Dad’s Club after he came across a listing on a popular parenting website of more than a dozen parent clubs in his area, only one of which claimed to be inclusive of dads. But even then, he found it had zero actual dad members. So, enjoy this humorous peek into the psyche of a stay-at-home dad in need of a little grown-up connection. And if you see him and his son at the record store, please invite him out for coffee.</p>
      <p><strong>Minutes for Will’s Best Dad Group EVER</strong></p>
      
      <p><strong>Call to Order</strong> </p>
      <p>A general meeting of Will’s Best Dad Group EVER was held on June 14 on the living room rug, near the overturned modem. It began at 7:54 a.m. and was presided over by Will, with Will as secretary.</p>
      
      <p><strong>Attendees</strong> </p>
      <p>Voting members in attendance included Will. Guests in attendance included Aristides, who is ineligible for voting membership because he is not a dad and also because he is a baby. Guests of guests in attendance included the twenty-three-dollar baby doll that smells like strawberries on account of the phthalates, but that Will had to buy because the lady at the fancy toy store caught Aristides gnawing on it. Members not in attendance included Dave, but he definitely will try to make it sometime, it’s just been crazy lately LOL, next week is looking better though, he’ll hit us up.</p>
      
      <p><strong>Approval of Minutes </strong>
      A motion to approve the minutes of the previous meeting (June 13, 11:47 p.m.) was made by Will and seconded by Will. An objection was raised by Aristides but was overruled because he is a baby, plus, honestly, on what grounds? An objection was then raised by Aristides to the overruling, which was also overruled, then objected to by Aristides, then overruled again, and then someone threw a maraca. A recess of one hour and thirty-five minutes was declared at this point.</p>
      
      <p><strong>Officers’ Reports</strong> </p>
      <p>Upon resumption of the meeting, the treasurer’s report was presented by Will. He stated that funding has been requested for double the projected Little Swimmers Huggies because basically, you have to sign up for Baby and Me swim class on their super janky website? So he accidentally signed up for lessons forty miles away, but when he tried to correct it, he signed up for a second class nearby, which is at 6:30 Sunday mornings, but he’s lucky he got in at all, because we all know the moms around here do. not. play. when it comes to Baby and Me swim class. But now Aristides will be twice as good a swimmer as their kids.</p>
      
      <p>The capital assets report was presented by Will. He said that coffee levels are critical because while his back was turned for he swears five seconds while he was flipping the Birds and Sounds of the British Countryside record, Aristides upended the thermos and coffee inundated the hospitality area, rendering everyone coffeeless and the last six pages of Little Blue Truck permanently brown.</p>
      
      <p>The social secretary’s report was presented by Will. At 2:30 this afternoon there will be an outing to the record store and he will say hey to that one dude behind the counter who always says hey.</p>
      
      <p><strong>Main Motions </strong></p>
      <p>Motion: Moved by Cool Will and seconded by Cool Will that somebody get the modem back on the windowsill, fire that sucker up, and do a Buy It Now on that sweet OG vinyl copy of Motörhead’s Ace of Spades off eBay before some primrose-path non-dad wakes up from his second nap of the day in a sunbeam somewhere, stretches self-indulgently, takes a sip of delicious hot coffee, and filches it.</p>
      
      <p>Counterargument by Lame Will claims that Cool Will will never listen to it because face it, man, those days are gone and now it’s pretty much nature sounds 24-7. The motion carried with 1 yea in favor and 0 nays against, because Lame Will can suck it. Aristides will totally dig that record in fifteen years.</p>
      
      <p>Motion: Moved by Will and seconded by Will that Will’s Best Dad Group EVER merge with Dave’s Dads Starring Dave! The motion was tabled with 1 yea in favor and 0 nays against after Dave couldn’t make it out after all, we gotta make it happen soon though my friend </p>
      
      <p><strong>Announcements</strong></p>
      <p>Aristides has four teeth.</p>
      
      <p>At 4:30 there will be a parenting class at O’Toole’s titled It’s OK to Bring the Kid If They Also Sell Fries: Six Ways to Distinguish a Bar from a Bar & Grill.</p>
      
      <p>Don’t forget, at 6:55 there’s the special Goodwill dads-only night out! Come one, come all to “get down” on the floor by the electronics bins and dig around for a new remote to replace the one that just drowned in the toilet. Semiformal attire: no yoga pants, please!</p>
      
      <p><strong>Emergency Incidental Main Motion </strong></p>
      <p>Aristides moved that despite his status as Guest, he be allowed the floor. Request, however unorthodox, was allowed. Aristides petitioned for amendment of by-laws, stating that he should be allowed voting membership on the grounds that dada. Da-da. Daddy. A gasp rose through the gallery. Order was called for. Order, I say!</p>
      
      <p>A recess was called while Will filled a bottle. Upon resumption of the meeting, the motion carried with 2 yeas in favor and 0 nays against.</p>
      
      <p><strong>Adjournment</strong> </p>
      <p>Aristides moved that the meeting adjourn and reconvene under the slide at the playground where we found that worm last time. This was seconded at 9:52 a.m.</p>
      
        <p>Respectfully submitted by </p>
        <p>Will, Secretary </p>
        <p>Will and Aristides’s Best Dad Group EVER </p>
        <p>June 14, 2019</p>
      ",

      "<p>It took something that almost broke me for me to find my voice. I was at work one day, and I immediately knew something was wrong. I was a graphic designer, so I was constantly looking at color, balance, and layout. That day, my vision seemed darker than usual on the left. I also taught a weekly dance class, and my balance suddenly felt off. I made an appointment with my eye doctor right away. She could see my concern, and although she couldn’t spot anything out of the ordinary, she sent me to a specialist just to make sure. The specialist said the same thing—nothing out of the ordinary. He suggested that maybe I was feeling tired because I had a small child at home. I almost accepted that answer, but I knew myself better than that.</p>
      <p>To be frank, it bothered me that a diagnosis of “tired new mom” seemed to be enough for him. Before I had by daughter Quinn I probably would have let this go, but knowing I had this little person to take care of, advocating for my health wasn’t just advocating for myself. I took some time to observe my eyesight. Soon, there were other symptoms. My teeth started feeling sensitive on the left side. I was overdue for a check-up anyway, so I brought it up during my appointment. I was sent to another doctor, who sent me to another doctor who finally ordered an MRI. I was chatting with the MRI technician during the scan, when, glancing at the images, his demeanor completely changed. He didn’t have to say anything, his eyes said it all. I whispered to Jay, my husband, “I think something is wrong.”</p>
      <p>Jay tried to stay positive. “We’ll wait to see what the doctor says,” he told me. I’ve always considered myself strong. It’s a point of pride, that I feel like I can physically take on anything. I immigrated here when I was 9-years-old and took care of my sisters while my parents worked night shifts. I had to grow up fast. Then, after having Quinn, I especially felt like a badass. My pregnancy wasn’t easy and labor felt like a lifetime achievement. After getting through childbirth, I wanted to high-five all mothers. But this big unknown? I wasn’t prepared for this type of emotional turmoil.</p>
      <p>By the end of the day, I got the call: “There’s a golf ball size tumor located between your left nasal cavity and cranial nerves.” My heart felt heavy, I didn’t know how to process it. All I knew was I needed to get a biopsy and then we would go from there. But then what? They even suggested that the tumor’s rapid growth may have been a result of my pregnancy. However it got there, it needed to be taken out or there could be more complications down the road. So, I was back to waiting—the part that I wasn’t great at, and not at all prepared for. Waiting in that room (so many rooms), getting tested, and then waiting to hear back. It was a terrible cycle. I had to advocate for myself and call to remind them, “Hi, remember me? I’m still here…waiting.”</p>
      <p>I was told to stop breastfeeding Quinn because of all the pain medication I would have to take. That truly was one of the saddest days for me. I wanted it to be natural, on our own time, but instead it was forced. It had taken me 6 weeks for her to latch after she was born. That was its own intense journey. I sobbed alone as Quinn called for me while my husband had to console her to sleep. I felt lonely. Then my mind started going to dark place—I would cycle through possibilities that didn’t even exist. Stories and situations completely fabricated by my desperation to find answers. I felt broken. It took three biopsies to find out it was benign. I still had a series of surgeries ahead of me. I know I should have been more thankful that it wasn’t cancer, but what followed took over my life for about a year and a half. The doctors were able to access everything through the roof of my mouth instead of slicing into my skull, which was amazing, but also made for a different type of intense and invasive procedure. In order to remove the tumor, they took out almost all of my top left teeth along with 3/4 off the roof of my mouth. Mentally accepting that process was hard, and physically it was no easier. It took three surgeries to completely remove the tumor, and another three to reconstruct the inside of my mouth. In between each procedure was a whole lot of waiting. </p>
      ",

      "<p>In Chinese medicine, summer is considered the season of abundance, the time of the year when energy is at its peak, the warm weather and extra sunlight permitting us more time to bring our bodies back into balance through restorative and uplifting activities. To that end, here’s why acupuncture is one ritual worth adding to your regimen now, and for the foreseeable future.<p>
      <strong><p>It’s a 2,000-year-old science</p></strong>
      <p>An ancient practice of integrative medicine, acupuncture entails pricking the skin with thin needles at strategic points to alleviate pain and treat various physical, mental, and emotional conditions. It’s designed to balance the flow of one’s life force energy, also known as Qi or Prana in Chinese and Ayurvedic medicines respectively, through specific pathways of the body known as meridians to 'create equilibrium and harmony,' says Juhi Singh, an acupuncturist, Oriental medicine specialist, Chinese herbalist, and founder of the Juhi Center in New York City. 'If you don’t fix an imbalance, you can’t fix the problem because all you’re ever doing is masking it,' explains Singh. 'Acupuncture ensures that energy is moving evenly through all of its channels by removing blockages and correcting underlying imbalances that have been sitting in the body for many, many years.'</p>
      <strong><p>It’s a natural way to manage pain</p></strong>
      <p>'Acupuncture is beneficial for any kind of inflammation,' says Singh, 'because when you insert a needle into a specific location of the body, you’re causing the release of endorphins, which are the chemicals that your body produces naturally to promote self-healing.' As it activates the body’s natural pain-killing hormones, the treatment is used to treat a wide spectrum of acute and chronic health conditions, including back pain, osteoarthritis, headaches, and indigestion. When pain is acute, like if someone has thrown out their back, acupuncture can produce fairly quick relief, Singh explains. 'But when it’s a more insidious condition, like migraines or Crohn’s disease, it can take longer to see results.'</p>
      <strong><p>It will increase longevity</p></strong>
      <p>Acupuncture can also be used to prevent pain and stop illness before they happen. “Oftentimes, patients will say to me, ‘There’s nothing wrong, why do I need it?’ and I say, ‘That’s exactly when you should do it.’ Likening acupuncture to exercising or taking vitamins, Singh believes it’s just as much of a tool for better health and longevity. Not to mention, it can be more holistic and customized at a time when many feel that healthcare is lacking personalization. 'It’s a precise science that’s never a one-size-fits-all approach,' she says. 'No two people will ever get the same treatment. It’s a very tailored approach to health care.'</p>
      "
      ].sample,
      image: [
        "https://res.cloudinary.com/dplpreov/image/upload/v1562953729/boy-children-couple-2253879_dygbzf.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562952735/baby-boy-child-1661818_sih1iz.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562952734/adult-aerobics-backlit-248139_eczhku.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562952734/assorted-diet-edible-247685_jqrdqo.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562951991/child-children-cute-160994_feilwr.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562951991/child-girl-kid-12165_smr0sr.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562963592/beautiful-blur-bridal-256737_ko0zan.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562963597/adorable-baby-baby-clothes-326583_o5khrc.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562963601/animal-cute-family-159864_hkjixs.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562963612/art-backlit-beach-256807_apfwbd.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562963616/beach-children-family-39691_vmncg2.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562966290/adorable-animal-animal-photography-1183434_wwyeva.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562966295/baby-shower-birthday-buffet-587741_h3in8u.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562966301/baby-clothes-blurred-background-clothesline-2565272_ct50yi.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562966308/adult-art-baby-235243_rl747q.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1562966313/adorable-animal-baby-230785_ypl6ln.jpg",
        'https://res.cloudinary.com/dplpreov/image/upload/v1563226750/black-friday-fashion-friends-1345082_tfrunc.jpg',
        "https://res.cloudinary.com/dplpreov/image/upload/v1563226750/alcoholic-beverage-beverage-citrus-1232152_xp3hid.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1563226750/blur-close-up-dairy-product-376464_t3x6qk.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1563226750/carrots-carrying-colorful-1389103_zzqb7s.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1563226750/active-aerobics-balance-868483_tibmi7.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1563579467/buildings-cellphone-cheerful-1586486_myuxbw.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1563579466/bake-bakery-baking-1251179_enjidd.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1563579466/action-active-adult-371049_lznjiq.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1563579273/boys-children-cute-1094072_nwvm38.jpg",
        "https://res.cloudinary.com/dplpreov/image/upload/v1563579273/beautiful-casual-cute-1313809_ccgx15.jpg"
      ].sample)
    
      1.times do
        cat.posts << post
  
    end
  end
end

puts "6 Categories Containing 4 Posts Each Created"
